services:
  postgres:
    image: postgres:15-alpine
    container_name: short_links_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - short_links_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: short_links_backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/short_links_db
      NODE_ENV: development
      APP_PORT: 3001
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - short_links_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: short_links_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - short_links_network

volumes:
  postgres_data:

networks:
  short_links_network:
    driver: bridge
